### ISSUE TITLE
Decide on encoding/decoding format

### ISSUE THREAD

**Issue by Jinglan** [plasma-group/pigi#131]

**Comment by Jinglan** [comment]
`exitDeposit(exitStart: uint, exitEnd: uint, depositEnd: uint, claimabilityWitness:bytes)` - allows users to submit an exit on a deposited state

Both of the above store an exit struct in `self.exits[self.exitNonce]` and `increment self.exitNonce`.

Sets the claim's `ethBlockRedeemable to: eth.block + self.CHALLENGE_PERIOD + state.predicateAddress.getAdditionalLockup(state)`

In this case, the `update.plasmaBlockNumber` comes from the `deposit.precedingPlasmaBlockNumber`

**Comment by Jinglan** [comment]
Perhaps ABI

**Comment by karlfloersch** [comment]
Using abi encoding <3
