### ISSUE TITLE
Add basic documentation for `vyper-js`

### ISSUE THREAD

**Issue by kfichter** [plasma-group/pigi#184]
## Description

We need some basic documentation for `vyper-js`. We currently only have a very basic [README](https://github.com/plasma-group/pigi/blob/3fbe2e9a96e21a51d47744aa220287ce9c9a8051/packages/vyper-js/README.md)that explains `vyper-js` at a high-level. We've added a [scaffold](https://github.com/plasma-group/pigi/tree/a80bf831fdca532e5c23f856e86e67cd64833be0/packages/docs/src/vyper-js) for `vyper-js` docs that we want to fill in!

If you'd like to tackle this issue, please read through the contextual information below. It explains more about `vyper-js`, what sort of documentation we're looking for, and how we usually handle our docs pages. Hopefully this information makes the documentation process as easy as possible :-).

## `vyper-js` 101

`vyper-js` is a simple JavaScript wrapper around the [Vyper compiler](https://vyper.readthedocs.io/en/latest/). It allows you to compile Vyper files from a inside JavaScript app and returns nicely formatted JavaScript objects. It's very similar to [solc-js](https://github.com/ethereum/solc-js), a JavaScript wrapper around the Solidity compiler.

## `@pigi` Documentation 101

Plasma Group uses [sphinx](http://www.sphinx-doc.org/en/master/) for its documentation. It might be helpful to check out the source code for some of our other documentation projects (like [`@pigi/utils`](https://github.com/plasma-group/pigi/tree/a80bf831fdca532e5c23f856e86e67cd64833be0/packages/docs/src/utils)) to get a better understanding of how sphinx works. We're using [reStructuredText](http://docutils.sourceforge.net/rst.html) instead of Markdown, primarily because it's the format best supported by [readthedocs](TODO).

Please work on your documentation in the [vyper-js docs](https://github.com/plasma-group/pigi/tree/a80bf831fdca532e5c23f856e86e67cd64833be0/packages/docs/src/vyper-js) folder that we've set up inside this monorepo!)

## Documentation Needs

We're looking for documentation that explains:

1. What `vyper-js` does at a high-level.
2. Any necessary pre-requisites to using `vyper-js` (Node.js, npm, [Vyper compiler](https://vyper.readthedocs.io/en/latest/installing-vyper.html)).

**Comment by ChrisChinchilla** [comment]
And if you have questions on documentation and good technical writing, feel free to contact me here, or in the #kauri channel of the Ethereal Discord server https://discord.gg/w8CbfQ

**Comment by writeprovidence** [comment]
currently working on this project, will soon send my work.
