### ISSUE TITLE
[@pigi/contracts] Basic Generalized Plasma Contract Prototypes

### ISSUE THREAD

**Issue by karlfloersch** [plasma-group/pigi#221]
The [Generalized Plasma Specification](http://spec.plasma.group) lays out a [set of smart contracts](http://spec.plasma.group/en/latest/src/02-contracts/contracts-overview.html) that a compliant implementation must include. We need to prototype these contracts and add basic tests.

Contracts to write:
- [ ] `Commitment.sol`
- [ ] `Deposit.sol`
- [ ] `OwnershipPredicate.sol`

Notes:
- `Commitment.sol` can stub `verifyInclusion` for this implementation.

**Comment by JGcarv** [comment]
Hello!

Is there anyone working on this issue yet? I can help.

I saw that the three contracts are already there, but are they done or do they need a bit more work?

Thank you!
