### ISSUE TITLE
Implement StateQuery interface

### ISSUE THREAD

**Issue by Jinglan** [plasma-group/pigi#237]
```
interface StateQuery {
  plasmaContract: string
  predicateAddress: string
  start?: number
  end?: number
  method: string
  params: string[]
  filter?: Expression
}
```

Description:
Represents a query for some information about the current state.

Fields:
`plasmaContract` - string: Address of the plasma contract to query. Clients may track multiple plasma contracts, so this parameter is necessary to resolve the correct data.
`predicateAddress` - string: Address of the predicate to query.
`start?` - number: Start of the range to query. If not provided, will default to the 0.
`end?` - number: End of the range to query. If not provided, will default to the max range value.
`method` - string: Name of the method to call.
`params` - string[]: List of parameters to the call.
`filter?` - Expression: An Expression to use to filter results. May be omitted to return all results.

**Comment by willmeister** [comment]
@karlfloersch @ben-chain is anything else required on this? Looks like this was implemented by @ben-chain here: https://github.com/plasma-group/pigi/blob/master/packages/core/src/types/serialization/state.interface.ts#L26
