### ISSUE TITLE
Implement StateQueryResult interface

### ISSUE THREAD

**Issue by Jinglan** [plasma-group/pigi#238]
```
interface StateQueryResult {
  stateUpdate: StateUpdate
  result: string[]
}
```

Description:
Element of the list of results returned when a client makes a state query.

Fields:
`stateUpdate` - StateUpdate: StateUpdate object to which the result pertains.
`result` - string[]: Result values of the query corresponding to the output values described in the Predicate API.

**Comment by willmeister** [comment]
@karlfloersch @ben-chain is anything else required on this? Looks like this was implemented by @ben-chain here: https://github.com/plasma-group/pigi/blob/master/packages/core/src/types/serialization/state.interface.ts#L36
