### ISSUE TITLE
Create an interface for deposit contracts

### ISSUE THREAD

**Issue by kfichter** [plasma-group/pigi#262]
[Deposit contracts](http://spec.plasma.group/en/latest/src/02-contracts/deposit-contract.html) hold user funds when those funds are "deposited" into the plasma chain. The Generalized Plasma Specification describes an interface for deposit contracts, so we should create an [interface](https://solidity.readthedocs.io/en/v0.4.24/contracts.html#interfaces) based on the specified API.

**Comment by shonjs** [comment]
If this is not done yet, I can.
