### ISSUE TITLE
Implement BlockDB

### ISSUE THREAD

**Issue by kfichter** [plasma-group/pigi#266]
[BlockDB](http://spec.plasma.group/en/latest/src/06-operator-architecture/block-db.html) is a database wrapper used by the [BlockManager](http://spec.plasma.group/en/latest/src/06-operator-architecture/block-manager.html) to store information about the next block to be published.

Tasks:
- [ ] Create an interface for `BlockDB`.
- [ ] Implement `BlockDB`.

**Comment by willmeister** [comment]
Is included within #325
