### ISSUE TITLE
Small state manager fixes

### ISSUE THREAD

**Issue by ben-chain** [plasma-group/pigi#295]
**Is your feature request related to a problem? Please describe.**
We have a couple of small issues which need to be resolved in the state manager.  I've found the following small hiccups in functionality:
- [x] does not pass `inBlock` to the plugin `executeStateTransition`
- [x] does not intersect `verifiedStateUpdate` with the output of `executeStateTransition`, intersects it with `transaction.range` instead
- [x] does not pass a `witness` around `executeTransaction`

**Describe the solution you'd like**
Need to:
- pass `inBlock` properly
- intersect ranges properly
- add witness passing to interfaces and functions

**Comment by ben-chain** [comment]
@willmeister I just realized that I'd made an issue for some of the things you're addressing with this latest PR, so we can reference this as being fixed by the PR.

Also, note that the second bullet here is needed even moreso now that we'll have ``executeStateTransition`` return a state object instead of a SU with range.

**Comment by karlfloersch** [comment]
Iced boiii
