### ISSUE TITLE
Figure out how to handle `Deposit` as a `StateObject`

### ISSUE THREAD

**Issue by kfichter** [plasma-group/pigi#34]
The base component of our plasma chain design is something called a [StateObject](https://github.com/plasma-group/pigi/blob/master/packages/utils/src/state-object.ts). Everything on the plasma chain is considered a state object, whether that's an account, a coin, a contract, etc etc. The current head state for a user consists of a set of state objects. Transactions take old state objects and transform them into new ones.

We need to figure out exactly how to handle deposits within this framework. Deposits are special transactions that "create" the object on the plasma chain.

We want to come up with a standard "Deposit" transaction that can be applied to the [StateManager](https://github.com/plasma-group/pigi/blob/master/packages/core/src/utils/state-manager.ts) such that the specified range is initialized in some way. I'm not exactly sure how this should be done. My biggest question is whether it's useful for deposits to be something other than simple ownership. If so, state object information (predicate, data, etc) need to be specified in the deposit.

**Comment by ben-chain** [comment]
Quick note--in new spec, deposits will now specify a state object for the deposit, so this might make things easier--just pull from the event
