### ISSUE TITLE
TypeScript Tag

### ISSUE THREAD

**Issue by burrrata** [plasma-group/pigi#35]
Looking through the open issues and many of them involve TypeScript. It would be helpful to create a TS tag for these. Might also be good to add tags for other languages/frameworks too. Then as new issues come up it'll be easier for new contributors to dig in and get started.

**Comment by kfichter** [comment]
This is a really good point - I’ll make a label for it and tag things in a bit!

**Comment by kfichter** [comment]
Done, thanks for the suggestion :+1:
