### ISSUE TITLE
Internal Message Pub/Sub

### ISSUE THREAD

**Issue by willmeister** [plasma-group/pigi#351]
This may need to be broken down into multiple issues.

Note: Make this reasonably generic so we can add different pub/sub implementations.

**Comment by Jinglan** [comment]
MVP for this is just ethereum (before devcon)

**Comment by willmeister** [comment]
This can really be pared down to save time before Devcon. Instead of making this generic and awesome in all cases, we can quickly do something very specific to Rollup. Updated estimate: 2 or 3?
