### ISSUE TITLE
Design/Implement Decision Storage

### ISSUE THREAD

**Issue by karlfloersch** [plasma-group/pigi#362]
Figure out the best way to inject a LevelDB into deciders & organize this in logical buckets that don't overlap (eg. access the wrong bucket).

**Comment by willmeister** [comment]
Labeling `misestimated` because this took Ben, Karl, and me a bit of time to talk through the different cases. We spent a bit of time trying to design for every possible case instead of trying to design an approach that would support, but not necessarily envelop, every possible case.
