### ISSUE TITLE
Stand-alone Data Stores used by Deciders

### ISSUE THREAD

**Issue by willmeister** [plasma-group/pigi#381]
This ticket encompasses:
* Creating individual data stores for necessary `Decider` data
* Injecting these stores into `Deciders`
* Updating references in unit tests
* Thinking through (and implementing if possible) a way to let all data stores know about all incoming and outgoing messages so they may store any pertinent info
* *Most Importantly* This should eliminate the need for a witness (only for these specific deciders)

Details [here](https://hackmd.io/ycrtl9CNT12S3TVC_7z8fQ).

**Comment by ben-chain** [comment]
Sweet!  Would add further that this should remove the need for the decider interface/inputs to accept witnesses--at least for the examples we have on the docket so far.
