### ISSUE TITLE
Add page that explains why plasma cash-like designs makes it possible for clients to be lightweight

### ISSUE THREAD

**Issue by kfichter** [plasma-group/pigi#42]
[Plasma Cash](https://www.learnplasma.org/en/learn/cash.html) is a design in the plasma family that vastly reduces the amount of data each individual user needs to store. Unfortunately there aren't a lot of resources that explain (simply!) why this is the case.

It'd be great to add a page to the [Plasma Group docs](https://github.com/plasma-group/pigi/tree/master/packages/docs/src/pg) that explains how plasma chain designs in the Plasma Cash family make it possible for clients to be very light.

These docs should explain:

1. The basic workings of plasma cash (especially its use of [Sparse Merkle Trees](https://medium.com/@kelvinfichter/whats-a-sparse-merkle-tree-acda70aeb837)). 
2. Why the sparse merkle tree means such a huge reduction in storage over Plasma MVP.
3. The advantages of this storage reduction (low-resource clients).

## Resources

As always, this can be a fairly complex subject. If you'd like to tackle this project but don't know where to start, I highly recommend checking out the [LearnPlasma article on Plasma Cash](https://www.learnplasma.org/en/learn/cash.html). Feel free to reach out to me if you'd like to schedule a call to go over this in more detail!

**Comment by ChrisChinchilla** [comment]
And if you have questions on documentation and good technical writing, feel free to contact me here, or in the #kauri channel of the Ethereal Discord server https://discord.gg/w8CbfQ

**Comment by aerophile** [comment]
I'm starting on this one.
