### ISSUE TITLE
Aggregator State Cache

### ISSUE THREAD

**Issue by karlfloersch** [plasma-group/pigi#443]
**Is your feature request related to a problem? Please describe.**
The aggregator is going to get **pummeled** with `getBalance(...)` requests once we go live. If we aren't smart we could run into issues where we can't support all of the balance requests. If we were to for instance respond to the balance requests with our aggregator & query the DB every time we'd quickly be overloaded.

**Describe the solution you'd like**
There are two main options that I see.

### 1) Serve *the last update* for every account & a signature guaranteeing that this was the last update for that account up until the current block
This is for sure the most performant way to go. The way this works is we create an intermediate server (between the aggregator & the client) which caches the receipts that the aggregator sends every time they update an account.

Further requests to this server respond with signed messages of the form:
```
signedBalancesQueryResult = [signature, mostRecentBalancesReceipt, currentBlock]
```

A fraud proof would be of the form:
```
fraudProof = [signedBalancesQueryResult, maliciouslyExcludedStateUpdate, excludedStateRoot]
```
and the blockchain would check that `excludedStateRoot.blockNumber > signedBalancesQueryResult.mostRecentBalancesReceipt.blockNumber && excludedStateRoot.blockNumber < signedBalancesQueryResult.currentBlock`

Could use some better variable names but I think you get the idea.

Advantage: Speed
Disadvantage: Complexity? Fraud proof format is a bit weird. That said, this could technically be the only way we implement fraud proofs for aggregator state receipts.

### 2) Serve an actual inclusion proof for the most recent block, but do this in a different server than the aggregator

This is just adding a server between the aggregator and user which specializes in serving in order to lighten the load of the aggregator. Upside of this is that it's less specialized & can serve inclusion proofs for the *current* block as opposed to the last updated block.

However, the downside is that for every state update we need to make log(TREE_DEPTH) updates to our DB (that's prolly fine), but also we need to make log(TREE_DEPTH) queries to our DB for every getBalance request. This could be fine but if we expect TONS of get balance requests it's not as good as 1 query per request in the former solution.

**Comment by ben-chain** [comment]
Nice writeup!  Currently I believe things look more like #2.  However, since we're already doing a mapping between account to storage slot, option 1 might not be craaazy complex.

I'm a little confused about the fraud proof structure proposed there though.  So far aggregator promise for a balance is a signed state root, its block and transition number, and any accompanying inclusion proof.  See [here](https://github.com/plasma-group/pigi/pull/442/files#diff-d5d9e17ca23fc176fe28e48007444f9aR115).  I'm a little confused by how the fraud proof scheme you've described would work.

**Comment by karlfloersch** [comment]
> a balance is a signed state root, its block and transition number, and any accompanying inclusion proof

So I'm saying you provide this for an outdated block, and a simple signature which says "Hey I know this proof is out of date, but I promise there's nothing more recent between then and now" -- this way we can serve out of date inclusion proofs to users.

That said totally agree that (2) is much closer to what we're already doing & prolly significantly easier.
