### ISSUE TITLE
Handle Aggregator Failure

### ISSUE THREAD

**Issue by Jinglan** [plasma-group/pigi#452]
This could be Aggregators always picking up exactly where they left off but more likely is the wallet acknowledging that the Aggregator's signature means nothing if they don't publish another block. Need to think through this UX and make sure we're covered.

In our case, we'll only have one aggregator (maybe represented by many different services), so that aggregator cannot make promises, fail, and then come up and start new, publishing new blocks without incorporating those promises.

**Comment by willmeister** [comment]
Included in #474
