### ISSUE TITLE
Simplify transitioner & wallet

### ISSUE THREAD

**Issue by karlfloersch** [plasma-group/pigi#461]
The UnipigTransitioner & the DefaultWallet are a bit over complicated. Issues include:

1) UnipigTransitioner extends the wallet class but that doesn't seem right... instead maybe it should just be passed a reference.
2) The wallet class does very resource intensive encryption. Instead we should either have the ability to toggle encryption in our current wallet implementation, or a simplified wallet class.

**Comment by willmeister** [comment]
2
