### ISSUE TITLE
Fix Level BaseDB backend

### ISSUE THREAD

**Issue by karlfloersch** [plasma-group/pigi#462]
**Describe the bug**
Currently level is broken as a BaseDB backend. This is sad because Level allows us to persist on the browser and on the server. It'll be super useful once we have it working again & my guess is it won't be super hard to do.

**Steps to reproduce**

If you want to reproduce generally, you should get the bug by simply replacing your normal BaseDB initialization with level as is done here: https://github.com/karlfloersch/pigi/blob/feat/aggregator_deploy/packages/example-rollup/src/mock-aggregator.ts#L43-L48 

Note that in this example I use `levelOptions` but you don't have to include that. What that code does is it makes level return buffers which I thought might solve the problem but unfortunately didn't work. Still thought it might be useful information so I kept it in.

Creating a BaseDB with level:
`const stateDB = new BaseDB(level('state') as any)`

You can also reproduce in the `aggregator_deploy` branch by:
1. checkout the branch https://github.com/karlfloersch/pigi/tree/feat/aggregator_deploy
2. inside of example-rollup `yarn run aggregator` & `yarn serve`
3. open `localhost:8080` and you should see the error pop up on the aggregator logs. I get this:

```
  error:rollup-aggregator Error getting state for address [0x0000000000000000000000000000000000000000]! Cannot read property 'rootHash' of undefined, TypeError: Cannot read property 'rootHash' of undefined
  error:rollup-aggregator     at lock.acquire (/Users/karlfloersch/workspace/ethereum/pigi/packages/wallet/build/src/rollup-state-machine.js:40:60)
  error:rollup-aggregator     at processTicksAndRejections (internal/process/next_tick.js:81:5) +0ms
```

**Expected behavior**
It should just work with level out of the box

**Specifications**
 - Version: Node v11

**Comment by willmeister** [comment]
3
