### ISSUE TITLE
Submit aggregator blocks to Ethereum

### ISSUE THREAD

**Issue by karlfloersch** [plasma-group/pigi#464]
Should be as simple as sending an ethereum transaction which contains all of the abi encoded transitions to:

https://github.com/karlfloersch/pigi/blob/feat/contract_merklization/packages/contracts/contracts/RollupChain.sol#L50-L63

This should probably get triggered every minute OR when we get to 300 transitions.

**Comment by willmeister** [comment]
In PR #474
