### ISSUE TITLE
Determine new word for `operator`?

### ISSUE THREAD

**Issue by kfichter** [plasma-group/pigi#75]
Copy/pasted from issue by @karlfloersch:

Now that we've come up with this new fancy "generalized plasma" design, do we think we can rename operator? 

If so, do we like `committer`? or `accumulator`? maybe `accelerator` (though not suuuper into it)? 

Deff no reason to fret about this too much as I'm sure operator is probably fine but this probably won't change unless we are all unified in changing the meme. Note this is for reducing the feeling that this party has custody of funds.

**Comment by karlfloersch** [comment]
omg lol not changing operator
