### ISSUE TITLE
Add a page that explains what invalid withdrawals are and how they're challenged

### ISSUE THREAD

**Issue by kfichter** [plasma-group/pigi#78]
## Exits 101

Withdrawals of funds from the plasma chain ("exits") are a core part of plasma. In effect, each exit is a claim about the current state of the plasma chain along with an action as a result of that claim. For example, the claim might be "I claim that I had 100 ETH on the plasma chain at time T" and the action might be "I want to withdraw 100 ETH". 

Unfortunately it's not simple for the plasma chain smart contract to tell which exits are valid and which aren't. Usually, we end up having to use something called a "claim-challenge" game whereby an exit can be blocked with a challenge that proves the claim is invalid. 

## Tasks

We need to add a documentation page to the [Plasma Group docs](https://github.com/plasma-group/pigi/tree/master/packages/docs/src/pg) that explains what invalid withdrawals are and how challenges are used to resolve them. We basically just want a very intuitive article (diagrams would be great!) that explains in a nutshell:

1. How withdrawals work.
2. Why certain withdrawals can be invalid.
3. How challenges can be used to prevent invalid withdrawals.

## Resources

Withdrawals can be a fairly complex subject to write about! Feel free to reach out to me if you'd like to hop on a call to go through how withdrawals work in detail. You'll become a plasma expert in no time! :-)

**Comment by ChrisChinchilla** [comment]
And if you have questions on documentation and good technical writing, feel free to contact me here, or in the #kauri channel of the Ethereal Discord server https://discord.gg/w8CbfQ

**Comment by calchulus** [comment]
happy to help with this - has anyone else claimed this? Chris also working on getting you a draft for the bonding curves as well :)

**Comment by johngrantuk** [comment]
Hi, I'd also be interested on working on this, I'm no Plasma expert but this would be a nice way to learn.

**Comment by ben-chain** [comment]
Looks like some awesome folks are working on a [gitcoin contest](https://gitcoin.co/issue/kauri-io/Content/39/2877) for this and a few other documentation issues--huge thanks to Kauri for setting up!

**Comment by nanspro** [comment]
@kfichter what implementation of plasma are we talking about here? i suppose MVP, right?

**Comment by kfichter** [comment]
@nanspro actually plasma cash in this case!

**Comment by ChrisChinchilla** [comment]
To clarify everyone, this is for a competition, so you are all free to take on the work and submit, don't wait for anyone to approve you. But if you have questions, please ask!
